#cls_dict:
#  bare_soil:
#    color: [255, 0, 0]
#    cls: 0
#
#  building:
#    color: [255, 255, 0]
#    cls: 1
#
#  pavement:
#    color: [192, 192, 0]
#    cls: 2
#
#  road:
#    color: [0, 255, 0]
#    cls: 3
#
#  vegetation:
#    color: [128, 128, 128]
#    cls: 4
#
#  water:
#    color: [0, 0, 255]
#    cls: 5

cls_dict:
  bare_soil:
    color: [255, 255, 255]
    cls: 0

  building:
    color: [0, 0, 255]
    cls: 1

  pavement:
    color: [0, 255, 255]
    cls: 2

  road:
    color: [0, 255, 0]
    cls: 3

  vegetation:
    color: [255, 255, 128]
    cls: 4

  water:
    color: [255, 0, 0]
    cls: 5

